[package]
name = "simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
round = "0.1.0"
threadpool = "1.8.1"
num_cpus = "1.0"
clap = { version = "4.0", features = ["derive"] }
abm = { path = "abm" }
